name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  WINDOWS_X86_64_BACKENDS: media-foundation,directshow,mvs,daheng,icube
  WINDOWS_I686_BACKENDS: media-foundation,directshow,mvs,icube
  LINUX_BACKENDS: v4l,mvs,daheng,icube

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --workspace # --verbose
    - name: Run Example
      run: cargo run --features "${LINUX_BACKENDS}" --example all_cameras
    #- name: Run tests
    #  run: cargo test --verbose

  build-x86_64-pc-windows-gnu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install MinGW-w64
      run: sudo apt-get update && sudo apt-get install -y gcc-mingw-w64-x86-64
    - name: Setup target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --target x86_64-pc-windows-gnu --workspace
    - name: Build Example
      run: cargo build --target x86_64-pc-windows-gnu --features "${WINDOWS_X86_64_BACKENDS}" --example all_cameras

  build-i686-pc-windows-gnu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install MinGW-w64
      run: sudo apt-get update && sudo apt-get install -y gcc-mingw-w64-i686
    - name: Setup target
      run: rustup target add i686-pc-windows-gnu
    - name: Build
      run: cargo build --target i686-pc-windows-gnu --workspace
    - name: Build Example
      run: cargo build --target i686-pc-windows-gnu --features "${WINDOWS_I686_BACKENDS}" --example all_cameras

  build-x86_64-pc-windows-msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --workspace
    - name: Run Example
      run: cargo run --features "${WINDOWS_X86_64_BACKENDS}" --example all_cameras

  build-i686-pc-windows-msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --workspace
    - name: Run Example
      run: cargo run --features "${WINDOWS_I686_BACKENDS}" --example all_cameras
