use std::ffi::c_int;
use birb_vision_core::image::{self, DynamicImage, ImageBuffer};


pub fn decode_mv_image(width: u32, height: u32, data: &[u8], pixel_type: c_int) -> image::DynamicImage {
    match pixel_type {
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Undefined => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Mono1p => {
            let _data = data
                .iter()
                .map(|byte| (0..8).map(move |bit| ((byte >> bit) &1) << 7).map(|p| p as u8))// TODO not <<7! this way it never reaches 255!
                .flatten()
                .collect::<Vec<_>>();
            todo!()
        },
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Mono2p => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Mono4p => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Mono8 => {
            DynamicImage::ImageLuma8(ImageBuffer::from_vec(width, height, data.to_owned()).unwrap())
        },
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Mono8_Signed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Mono10 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Mono10_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Mono12 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Mono12_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Mono14 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Mono16 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerGR8 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerRG8 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerGB8 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerBG8 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerRBGG8 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerGR10 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerRG10 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerGB10 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerBG10 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerGR12 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerRG12 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerGB12 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerBG12 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerGR10_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerRG10_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerGB10_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerBG10_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerGR12_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerRG12_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerGB12_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerBG12_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerGR16 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerRG16 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerGB16 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BayerBG16 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_RGB8_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BGR8_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_RGBA8_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BGRA8_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_RGB10_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BGR10_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_RGB12_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BGR12_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_RGB16_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BGR16_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_RGBA16_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BGRA16_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_RGB10V1_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_RGB10V2_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_RGB12V1_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_RGB565_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_BGR565_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YUV411_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YUV422_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YUV422_YUYV_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YUV444_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YCBCR8_CBYCR => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YCBCR422_8 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YCBCR422_8_CBYCRY => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YCBCR411_8_CBYYCRYY => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YCBCR601_8_CBYCR => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YCBCR601_422_8 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YCBCR601_422_8_CBYCRY => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YCBCR601_411_8_CBYYCRYY => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YCBCR709_8_CBYCR => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YCBCR709_422_8 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YCBCR709_422_8_CBYCRY => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YCBCR709_411_8_CBYYCRYY => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YUV420SP_NV12 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_YUV420SP_NV21 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_RGB8_Planar => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_RGB10_Planar => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_RGB12_Planar => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_RGB16_Planar => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Jpeg => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Coord3D_ABC32f => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Coord3D_ABC32f_Planar => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Coord3D_AC32f => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_COORD3D_DEPTH_PLUS_MASK => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Coord3D_ABC32 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Coord3D_AB32f => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Coord3D_AB32 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Coord3D_AC32f_64 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Coord3D_AC32f_Planar => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Coord3D_AC32 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Coord3D_A32f => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Coord3D_A32 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Coord3D_C32f => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Coord3D_C32 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Coord3D_ABC16 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Coord3D_C16 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_Float32 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_Mono8 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_Mono10 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_Mono10_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_Mono12 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_Mono12_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_Mono16 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerGR8 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerRG8 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerGB8 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerBG8 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerRBGG8 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerGR10 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerRG10 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerGB10 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerBG10 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerGR12 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerRG12 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerGB12 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerBG12 => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerGR10_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerRG10_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerGB10_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerBG10_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerGR12_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerRG12_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerGB12_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BayerBG12_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_YUV422_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_YUV422_YUYV_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_RGB8_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BGR8_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_RGBA8_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BGRA8_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_RGB16_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BGR16_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_RGBA16_Packed => todo!(),
        mvs_sys::MvGvspPixelType_PixelType_Gvsp_HB_BGRA16_Packed => todo!(),
        _ => todo!(),
    }
}